name: Build Android App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - uses: android-actions/setup-android@v2

      - run: chmod +x ./gradlew

      - run: ./gradlew assembleDebug

      - uses: actions/upload-artifact@v4
        with:
          name: termux-gui-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
